# Vector Space Model

In [3]:
documents = [
    "whoever has hate for his brother is in the darkness and walks in the darkness",
    "hello darkness my old friend",
    "returning hate for hate multiplies hate adding deeper darkness to a night already devoid of stars darkness cannot drive out darkness only light can do that"
]

## Calculating Cosine Distance in Pandas

In [ ]:
import pandas as pd
from collections import Counter

tf = pd.DataFrame(
    [Counter(doc.split()) for doc in documents],
).fillna(0)
tf

In [ ]:
import numpy as np

def length(v):
  return np.sqrt((v ** 2).sum())

def cos_dist(v, w):
  return 1 - (v * w).sum() / (length(v) * length(w))

cos_dist(tf.loc[0], tf.loc[1]), cos_dist(tf.loc[0], tf.loc[2])

## Calculating Cosine Distance in Scikit-Learn

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

vec = CountVectorizer(token_pattern=r"\w+")
vec.fit(documents)
tf_matrix = vec.transform(documents)
tf_matrix.todense()

In [ ]:
from sklearn.metrics import pairwise_distances
pairwise_distances(tf_matrix[0, :], tf_matrix,
                   metric="cosine")

# tf-idf

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

# The options ensure that the numbers match our example above.
vec = TfidfVectorizer(smooth_idf=False, norm=None)
vec.fit(documents)
tfidf_matrix = vec.transform(documents)
tfidf_matrix.todense()

In [ ]:
pairwise_distances(tfidf_matrix[0, :], tfidf_matrix,
                   metric="cosine")

# Dr. Seuss Example

What Dr. Seuss book is most similar to _One Fish, Two Fish, Red Fish, Blue Fish_?

In [ ]:
seuss_dir = "http://dlsun.github.io/pods/data/drseuss/"
seuss_files = [
    "green_eggs_and_ham.txt", "cat_in_the_hat.txt",
    "fox_in_socks.txt", "how_the_grinch_stole_christmas.txt",
    "hop_on_pop.txt", "horton_hears_a_who.txt",
    "oh_the_places_youll_go.txt", "one_fish_two_fish.txt"]

In [ ]:
import requests
docs = {}
for filename in seuss_files:
    response = requests.get(seuss_dir + filename, "r")
    docs[filename] = response.text

In [13]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd

# Menggunakan dataset yang sudah ada
corpus = documents  # Menggunakan variabel documents yang sudah didefinisikan

# Representasi vektor dengan fokus pada kata kunci 'hate' dan 'darkness'
vectorizer = CountVectorizer(vocabulary=['hate', 'darkness'])
X = vectorizer.fit_transform(corpus)

# Menghitung Cosine Similarity antara Dokumen 0 dan semua dokumen
cos_sim = cosine_similarity(X[0:1], X)

# Menampilkan hasil dalam DataFrame
df = pd.DataFrame(X.toarray(), columns=['hate', 'darkness'])
df['Cosine Similarity to Doc 0'] = cos_sim.flatten()
df

   hate  darkness  Cosine Similarity to Doc 0
0     1         2                    1.000000
1     0         1                    0.894427
2     3         3                    0.948683

**Penjelasan CountVectorizer:** Alat ini mengubah teks menjadi representasi numerik berupa matriks frekuensi kata. Dalam contoh ini, kita batasi hanya pada kata "hate" dan "darkness" untuk fokus pada tema utama.

**Cosine Similarity:** Metrik ini memberikan nilai antara 0 hingga 1, di mana nilai yang lebih tinggi menunjukkan kesamaan yang lebih besar antara dua dokumen.

**Analisis:** Dokumen 2 menunjukkan kesamaan tinggi dengan Dokumen 0 meskipun memiliki frekuensi kata yang berbeda, menunjukkan arah topik yang serupa.

**Perbandingan dengan Euclidean Distance:** Jika menggunakan jarak Euclidean, Dokumen 2 mungkin terlihat sangat berbeda karena perbedaan frekuensi kata (3 vs 1 untuk 'hate', 3 vs 2 untuk 'darkness').

**Penerapan Nyata:** Konsep ini merupakan fondasi bagi mesin pencari dan sistem rekomendasi konten yang kita gunakan sehari-hari.

In [14]:
# Matriks Cosine Similarity Lengkap
full_cos_sim_matrix = cosine_similarity(X)

# Menampilkan matriks dalam format DataFrame untuk kemudahan pembacaan
cos_sim_df = pd.DataFrame(full_cos_sim_matrix, 
                          index=[f'Dokumen {i}' for i in range(len(corpus))], 
                          columns=[f'Dokumen {i}' for i in range(len(corpus))])
cos_sim_df

           Dokumen 0  Dokumen 1  Dokumen 2
Dokumen 0   1.000000   0.894427   0.948683
Dokumen 1   0.894427   1.000000   0.707107
Dokumen 2   0.948683   0.707107   1.000000